# Generated by Django 4.0.4 on 2022-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.TextField()),
                ('name', models.TextField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
