# Generated by Django 4.0.4 on 2022-05-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
        ('studentapp', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(db_column='courseId', on_delete=django.db.models.deletion.CASCADE, to='courseapp.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='studentapp.student'),
        ),
    ]
